### ISSUE TITLE
Original resolution not loaded

### ISSUE THREAD

**Issue by distantnative** [terrymun/Fluidbox#101]
I have the problem that even though my a-link-element is referencing the original image resolution instead of the thumb resolution that is used by the img-elemtn, the fluidbox still rather seems to show the thumb resolution: http://zu-fo.de/gallery-test

**Comment by terrymun** [comment]
I don't seem to be able to reproduce your issues—tested on OS X Yosemite, Chrome, Firefox, Safari and Opera. May I know which browser are you using?

**Comment by distantnative** [comment]
OS X Yosemite, Safari 8.0.3

In Fluidbox:
![screen shot 2015-01-31 at 17 59 03](https://cloud.githubusercontent.com/assets/3788865/5988870/fd940322-a972-11e4-87b3-df707bec8170.png)

The original image:
![screen shot 2015-01-31 at 17 59 36](https://cloud.githubusercontent.com/assets/3788865/5988871/fdbc32de-a972-11e4-8ce9-350c33f1f07c.png)

**Comment by terrymun** [comment]
Upon further inspection I realized that Safari does not like dealing with pseudo-elements in CSS transformed elements. An immediate fix would be removing the `::before` claractions in the file `fluidbox.css`. An alternative way of styling the loader will be implemented in the next release.

**Comment by distantnative** [comment]
That seems to work - thanks for the immediate fix, more important to me than the loader, but looking forward to the next release

**Comment by anthonyabraira** [comment]
I tried to do this: 

```
 /* .fluidbox-ghost::before { 		disabled */
  .fluidbox-ghost {
    animation: fluidboxLoading 1s infinite;
    /* You can replace this with any color you want, or even a loading gif if desired */
    background-color: rgba(255, 255, 255, 0.85);
    content: '';
    transform-style: preserve-3d;
    transition: all 0.25s ease-in-out;
    opacity: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    width: 20%;
    padding-bottom: 20%;
    /* Delay disapparing of loader for graceful transition */
    transition-delay: 0.125s; }
/*  .fluidbox-loading .fluidbox-ghost::before {		disabled */
  .fluidbox-loading .fluidbox-ghost {
    opacity: 1;
    transition-delay: 0; }
  .fluidbox-opened .fluidbox-ghost {
    transition-delay: 0, 0; }

/*# sourceMappingURL=fluidbox.css.map */
```

Was that what you meant?

**Comment by terrymun** [comment]
Nope. You will have to comment out the entire code block with `::before`, not just the single line.

Also, the SCSS file has to be compiled into CSS. It is not meant to be used as-is — and if you try to compile your code as above you will run into an error due to unclosed `{`.

**Comment by terrymun** [comment]
@distantnative A solution has been devised, which involves moving up the loader div one level up the DOM tree so it doesn't mess with Safari's rendenering of the scaled element `.fluidbox-ghost` and its background. Check out the latest commit: [2aad89d2bd](https://github.com/terrymun/Fluidbox/commit/2aad89d2bd026a22b9ebf1e3c89ca5d8367678b6)

I will stop short of publishing a new release, mainly because I want to do a bit more testing and see if the nest DOM manipulating and altered nesting affects other aspects of Fluidbox. So far I have tested in Chrome, Safari and Firefox, looking good :+1:
