### ISSUE TITLE
Zoom Animation Breaks After First Zoom

### ISSUE THREAD

**Issue by realph** [terrymun/Fluidbox#102]
I'm having an issue, where the first opening and closing of my lightbox looks great, but subsequent openings of the image just appear without the zoom animation. I've made a screen recording to help explain my issue.

http://cl.ly/Zc58/zoom720.mov

Any help with this is appreciated. Thanks in advance!

**Comment by terrymun** [comment]
What browser are you using? This behavior is only observed with Safari 8, for very strange reasons. However, a quick fix would be enabling the `immediateOpen` option.

**Comment by realph** [comment]
@terrymun `immediateOpen` seems to do the trick! Using Chrome (40.0.2214.94) om Mac.

**Comment by terrymun** [comment]
It's really unfortunate, because I have looked through the code and don't see why would have possibly cause this behavior. Fluidbox behaves as per usual in Chrome and Firefox, both on OS X Yosemite.

However I will add this to the known issues section in the readme :) thanks for reminding me!

**Comment by ihabovich** [comment]
`immediateOpen: true` did fix the problem for Chrome and Firefox browsers running on Windows OS.
