### ISSUE TITLE
Demo website tries to load resources over http even when acceessed via https.

### ISSUE THREAD

**Issue by hobarrera** [terrymun/Fluidbox#104]
The [demo website](https://terrymun.github.io/Fluidbox/) tries to load resources over http even when acceessed via https.

This results in several security errors in firefox, which blocks the resources, and denies access to them. As a result, the website does not work as intended.

See this [screenshot](http://i.imgur.com/27VacUY.png) for details.

**Comment by terrymun** [comment]
Issue fixed in demo now as of 92a894b, updated resource URLs to use protocol agnostic counterparts, i.e. `//` instead of `http://`.
