### ISSUE TITLE
Disable for IE9 or less

### ISSUE THREAD

**Issue by paul-frost** [terrymun/Fluidbox#106]
I don't mind that it doesn't work in IE9, but it's stopping the normal link behaviour. When you click, nothing happens, but you can right click and open in another tab/window. How can I allow the link to work as normal when the browser can't handle Fluidbox?

**Comment by terrymun** [comment]
The only way I can think of is to use [IE-specific conditional comments](https://msdn.microsoft.com/en-us/library/ms537512%28v=vs.85%29.aspx) to load the configuration settings for Fluidbox, e.g.:

```html
<!--[if gte IE 7]>
    <script src="fluidbox.js"></script>
    <script src="functions.js"></script>
<![endif]-->
```

**Comment by paul-frost** [comment]
Thanks Terry
