### ISSUE TITLE
Fluidbox overlay appearing without image

### ISSUE THREAD

**Issue by ntgxtreme** [terrymun/Fluidbox#108]
I'm unable to get Fluidbox functioning consistently on my site: http://tflsmedia.com/

If you click on the first portfolio entry, I've linked all of the images there. It works intermittently, and mostly doesn't.

When it doesn't, the overlay appears and the original image fades away, but the subsequent scaled image doesn't appear. However, if you inspect it in Chrome, it starts working until refreshed.

**Comment by terrymun** [comment]
From your site I can see that the enlarged image container, `.fluidbox-ghost` has incorrectly calculated dimensions, suggesting that the plugin did not have access to the image's natural width and height on runtime. Are you using a delayed/lazy loading, and if the images are dynamically added, implement `.fluidbox()` to these objects *after* the event?

**Comment by ntgxtreme** [comment]
Hi Terry,

The site is built off of a template that I modified, so I'm not certain how
it's all built, but the project pages do appear to be lazy loaded via
jQuery.

How does one go about implementing fluidbox after? I did notice that I had
to add the script to the project page and not the main page to get it to
trigger, but I presume that's not what you meant.

– Yih

**Comment by terrymun** [comment]
A way to implement it would be to implement Fluidbox after the images has been loaded. There has to be a success/loaded callback with the plugin, you simply have to initialize Fluidbox within that callback.
