### ISSUE TITLE
Fluidbox Not Working Properly with Browserify

### ISSUE THREAD

**Issue by realph** [terrymun/Fluidbox#109]
I'm trying to use Fluidbox with Browserify, but I'm running into an issue where the `.fluidbox-wrap`s are taller than the image inside it. See the illustration below:

![screen shot 2015-03-13 at 01 06 56](https://cloud.githubusercontent.com/assets/2334951/6631406/793dbab2-c91d-11e4-9bbc-81fc11f00eff.png)

The grey area shows how far the `.fluidbox-wrap`s have stretched. This is how I'm including the Fluidbox plugin:

**app.js**

    var $ = require('jquery');
    var fb = require('./vendors/fluidbox.js');

    fb();

    $('.gallery a[rel="lightbox"]').fluidbox({
       viewportFill: 0.9,
       immediateOpen: true
    });

**fluidbox.js**

    var jQuery = require('jquery');

    module.exports = function() {
      // Fluidbox plugin goes here
      ...
    };

For what it's worth, if I do it the traditional way, with two script tags (jQuery and Fluidbox from cdnjs) it works perfectly. No tall `.fluidbox-wrap`s. Any idea why this is happening?

Any help with this is appreciated. Thanks in advance!

P.S. Any chance of having this available via npm in the near future?

**Comment by terrymun** [comment]
Any error messages from the browser console?

As I have understood this plugin is available via npm, but it was implemented some time ago, perhaps it would require some updating. Or that the configuration file was lost at some point.

**Comment by realph** [comment]
No error messages in the console. Just a visual bug as shown above.

I can't seem to find the plugin on npm, either.

**Comment by realph** [comment]
@terrymun Okay, maybe it isn't isolated to Browserify. I've got a CodePen over here replicating the same issue. See how the `.fluidbox-wrap`s are taller than they should be? http://codepen.io/realph/pen/dPgrqx

**Comment by realph** [comment]
@terrymun It seems as if the `.fluidbox-ghost` element is causing the `.fluidbox-wrap`s height to stretch.

![screen shot 2015-03-13 at 16 30 39](https://cloud.githubusercontent.com/assets/2334951/6642682/76532374-c99e-11e4-9f56-64cd05b6c316.png)

Any ideas?

**Comment by terrymun** [comment]
That's because you're not including the Fluidbox styling in your Pen. Please refer to [installation instructions](https://github.com/terrymun/Fluidbox#installation).

**Comment by realph** [comment]
Sorry, I forgot to include the CSS in my CodePen. I did have the `fluidbox.scss` (installed with Bower) file in my actual project, but it seems like .scss was different to that in your latest commit. So I re-installed, specifying the latest git commit (078cd550f3) and seems to have done the job!

So, thanks for pointing out where the problem lay. I really appreciate you getting this thing up on npm too, it's an awesome plugin and your support is second-to-none. Thanks again, duder!
