### ISSUE TITLE
Open animation only works first time

### ISSUE THREAD

**Issue by DavGarcia** [terrymun/Fluidbox#110]
I ran into an issue on my web site where the open animation only occurs the first time the thumbnail is clicked. After that the open animation doesn't play out, the image just snaps between thumbnail and full size.

I thought it might be something I was doing wrong, but then I tried the demo page and noticed the same issue there. This is in Chrome 41, but I get the same problem in IE and Firefox, all on Windows (have not tested Mac.)

https://www.youtube.com/watch?v=wEYL7-U8cac

The console doesn't have any details regarding what went wrong.

**Comment by terrymun** [comment]
See #96.
