### ISSUE TITLE
Fluidbox with responsive images

### ISSUE THREAD

**Issue by joeldrapper** [terrymun/Fluidbox#111]
I'd like to use fluidbox with responsive images using the `<picture>` element. Is there any planned support for this?

**Comment by terrymun** [comment]
Hi there!

Future support for `<picture>` is planned, but no current plans are in place yet.

**Comment by anroots** [comment]
This would be highly appreciated.

**Comment by christophemarois** [comment]
+1

**Comment by Daniel0524** [comment]
In a similar vein, I discovered a [Codepen by you](http://codepen.io/terrymun/pen/mvHky/) whose implementation of a responsive image grid I really liked, that led me to your Fluidbox plugin which is also super cool, but I can't seem to get the two to work together.

Is this possible or no?

**Comment by terrymun** [comment]
@Daniel0524 I would assume that you have simply try to load both scripts at the same time? I wouldn't expect that to work out of the box for one reason—the responsive image gallery listens on the `$(window).load()` event, to ensure that the layout is only made when image dimensions are available. This means that the layout is finalised *after* Fluidbox has been implemented (assuming that you are binding the method to DOM elements on DOM ready, which is typical and also what I've used in the demos), also meaning that Fluidbox does not have access to the final image dimensions, messing the calculations up.

A patchwork solution though, is to bind Fluidbox only after the layout is completed. Of course you can setup custom events (using `.trigger()`) to listen to image load and layout completion, which then you will listen to the custom event bubbling up to the document (using `$(document).on()`) which subsequently binds Fluidbox.

The CodePen you have linked is more of a small experiment and is not meant for production—it should be ported over as a proper, full-fledged jQuery plugin but I don't see there's a demand for it now.

**Comment by terrymun** [comment]
`<picture>` is now being officially supported in v2.x.
