### ISSUE TITLE
Cycling through images

### ISSUE THREAD

**Issue by intermedion** [terrymun/Fluidbox#115]
In order to view each large image the user has to click on the image to open it, click again on the fluidbox to close the image, move the cursor to the next image, repeat clicks above and so on. A welcome addition would be to offer the user the option to cycle through the full size images either via the arrow keys, or by clicking on right/left arrow. This would eliminate the constant need to reposition the cursor to open each new image.

**Comment by terrymun** [comment]
Please refer to #80 and #81, as well as the [FAQ section](https://github.com/terrymun/Fluidbox#frequently-asked-questions) of readme.md.
