### ISSUE TITLE
Info: docs show old/incorrect closeTrigger selector

### ISSUE THREAD

**Issue by jools-r** [terrymun/Fluidbox#116]
Just an info: the docs here on Github and on the demo page show `#fluidbox-overlay`rather than `.fluidbox-overlay`. This may resolve closing problems with touch devices with custom close events (closed fluidbox reopens when you happen to click on the (invisible) original image).

**Comment by terrymun** [comment]
Thanks, will fix that in the next release—which might take some time. It will be fixed in the v2, where the plugin code will be completely refactored.
