### ISSUE TITLE
Issue When Dimensions of Thumbnail and Target Image Don't Match.

### ISSUE THREAD

**Issue by joshuapinter** [terrymun/Fluidbox#119]
I'm using a "zoom-cropped" thumbnail (100x100) and when clicking on the link it shows the target image but in the same "dimensions" as the thumbnail so the image looks distorted.

Is there a way to get around not having the exact same dimensions for both the thumbnail and target image?

For example, providing the target image dimensions?

Thanks!

Josh

**Comment by terrymun** [comment]
Hasn't this feature been implemented a few subversions ago? Are you using the latest version of Fluidbox?

**Comment by joshuapinter** [comment]
Hmm.. I'm on 1.4.2. Have some customizations so I haven't got the latest version, yet. Any idea what version it was implemented in?

**Comment by terrymun** [comment]
That was implemented in v1.4.0.
