### ISSUE TITLE
Zepto.js drop-in?

### ISSUE THREAD

**Issue by nybblr** [terrymun/Fluidbox#120]
From a quick perusal of the codebase, it looks like a lightweight-jQuery replacement like Zepto could work.

Any immediate red flags? I have a site I'd love to use this on, but for performance reasons we try to stick with Zepto.

**Comment by terrymun** [comment]
Interesting point, but Fluidbox relies rather heavily on the `.data()` object of jQuery, which is not supported in Zepto. What's your take?

ps: I'm also thinking about refactoring the code base for Fluidbox, but that'll happen slowly over summer.

**Comment by nybblr** [comment]
@terrymun interesting, I haven't ever used `data()` that way.

In a lot of places, it looks like the Fluidbox code could use the `.data('attr-name')` form instead, which is supported by Zepto. Is there a particular reason `.data()` needs to be used? Performance?

If so, it seems like Zepto already has most of the code there to do it, but isn't exposing it for some reason: https://github.com/madrobby/zepto/blob/master/src/data.js#L37

Thoughts?

**Comment by terrymun** [comment]
Data is used in order to store the relevant image dimensions in an easily accessible object form—manually initialising objects for each Fluidbox instance is probably going to be messy.
