### ISSUE TITLE
Disable Fluidbox on Slow Mobile Devices

### ISSUE THREAD

**Issue by realph** [terrymun/Fluidbox#121]
I've noticed Fluidbox's performance is a bit slow/choppy on older devices when running some browser testing this evening.

Is there a catch-all for slower mobile devices, so we can fallback to disabling the library if the device isn't up to the task?

Any help with this is appreciated. Thanks in advance!

**Comment by realph** [comment]
The README recommends disabling it altogether on mobile devices. Is there an easy way to do this?

**Comment by terrymun** [comment]
There is no catch-all for slower mobile devices—the most reliable way is to simply disable Fluidbox at small screen sizes. Currently the only way is to not initialize Fluidbox when the viewport dimensions are smaller than a certain threshold.

However, in v2, a destroy method will be implemented (such as [the one seen in one of my newer projects](http://terrymun.github.io/paver/demo/custom-triggers-events.html#custom-triggers__destroy-paver)) such that users can destroy Fluidbox instances as of when they like—including the possibility of doing so whenever the viewport is resized, or other criteria.

v2 requires rewriting most of Fluidbox codebase, which I hope will be done over the course of the summer.
