### ISSUE TITLE
Uncaught TypeError: $(...).fluidbox is not a function

### ISSUE THREAD

**Issue by SWalls** [terrymun/Fluidbox#123]
Using either jQuery 1.11.1 or 2.1.1, fluidbox does not work for me. I have followed the installation instructions carefully, making sure to include `jquery-1.11.1.min.js` (or `jquery-2.1.1.min.js`) before including `jquery.fluidbox.min.js`, with the following code after that:

```javascript
$(document).ready(function(){
    $('div.gallery a[rel="lightbox"]').fluidbox();
});
```

However, upon page load, I get the following error in the JavaScript console: `Uncaught TypeError: $(...).fluidbox is not a function`, generated from the previous code. What is going wrong?

Edit: Just to clarify, I am 100% certain the paths to the jQuery and fluidbox files are correct. Also, jQuery functions as expected for everything else on the page.

**Comment by terrymun** [comment]
Without seeing your implementation, there are several reasons why this is happening:

- Fluidbox is loaded after a minified library or script that do not have a closing trailing semicolon. 
- You are using the compatibility mode of jQuery, which means the `$` sign is not assigned as an alias for the plugin. Check if `$ === jQuery` is true. 
- Fluidbox.js is not being loaded. Check your network/resources tab of your inspector/developer tool in the browser to ensure that the file is loaded and the status code is 200.

**Comment by SWalls** [comment]
Thanks for responding so quickly, but unfortunately none of those were the source of the error.

Fluidbox is the very first script being loaded after jQuery (which is the first script), I've confirmed jQuery is not in compatibility mode (checking `$ === jQuery` does indeed return `true`), and the console reports a status code of 200 for the file `jquery.fluidbox.min.js` (until it's cached, at which point it reports a 304 non-modified status code as expected).

If you'd like to see my implementation, [this](http://www.codingnaked.com/post/gravl/) is one of the pages it's running on. There are quite a few external resources, but [`header.js`](http://www.soerenwalls.com/js/header.js) is the file that contains the call to `$(...).fluidbox()`, way at the bottom.

**Comment by SWalls** [comment]
Sorry for such a mysterious use-case, I've been trying to figure this out for that past 6 hours. If I may recommend something, perhaps it might be worthwhile to allow an alternate method of invocation for times when jQuery behaves unpredictably. Maybe something like:
```javascript
fluidbox.init("a");
```

**Comment by SWalls** [comment]
I figured it out! Something deep in my code was dynamically adding another jQuery file to my `<head>` tag, so I was effectively loading two different versions of jQuery, without calling `noConflit()`, which is a very bad idea. Sorry to have wasted your time, I was totally convinced nothing was wrong on my part. I just which the console had warned me of this in some way, jeez.

**Comment by jaker09** [comment]
SWalls, or terrymun, could you describe how you solved this problem. My code also seems to not be recognizing "fluidbox" as a function and i've tried all the other tests. I get true when $===jQuery, but I don't get a 200 in the network tab, i see a 304 unmodified. Is this the cause? I can describe my setup in more detail if needed. thanks.

**Comment by terrymun** [comment]
A code 200 simply means that the item is fetched from the browser cache (because its header has not expired), while a code 304 means a browser checked if the file has changed (and finds out that it is unmodified).

I don't see any issue in the HTTP codes you are getting. Are you sure Fluidbox is being loaded?

**Comment by jaker09** [comment]
Terry,
thanks for the reply. the issue had to do with the location of the src information, i had it in the head rather than in the end of the body where it seems to be working fine. thanks
