### ISSUE TITLE
Disabling Fluidbox on mobile devices

### ISSUE THREAD

**Issue by marktoce** [terrymun/Fluidbox#128]
Hello,

What is the best method for disabling Fluid box on mobile devices? 

Thanks!

**Comment by Jonathlee** [comment]
https://css-tricks.com/enquire-js-media-query-callbacks-in-javascript/

or

http://detectmobilebrowsers.com/

**Comment by terrymun** [comment]
Simply not implement Fluidbox on mobile devices? It might not be a good idea to sniff for the user agent—instead, you should decide if you want to bind Fluidbox or not depending on the screen resolution.

Fluidbox's code base is being rewritten to conform to the standard jQuery plugin format, so you should be able to destroy any instances after initialising it. It will be shipped as v2.

**Comment by dergraph** [comment]
pointer-events: none in a css query for mobile can prevent the event easily. thats how i did it
