### ISSUE TITLE
Is it possible to only work with a JPG?

### ISSUE THREAD

**Issue by paul-frost** [terrymun/Fluidbox#129]
Is it possible to configure it to only apply to a JPG, so PNG's & GIF's are ignored?

**Comment by r043v** [comment]
just apply the plugin onto the good selection ..

link to jpg :
$('a[href$=".jpg"]').fluidbox();

link to jpg with a picture inside :
$('a[href$=".jpg"] > img').parent().fluidbox();

**Comment by paul-frost** [comment]
Thanks for that.
But I still have a problem because I'm using this in a CMS teaxtarea and the wrapping of inserted images automatically adds the ahref, so I've stopped fluidbox working on it but now it just opens in a new tab, which is probably worse. I'll need to look at how to exclude the ahref being added to non JPG's.

**Comment by r043v** [comment]
you can try cancel the click event on gif & png links

$('a[href$=".jpg"]').fluidbox();
$('a[href$=".gif"],a[href$=".png"]').on('click',function(e){ e.preventDefault(); });

**Comment by terrymun** [comment]
Using attribute selectors to restrict Fluidbox to specific anchor elements based on the `href` value should work, as per @r043v's suggestion.

**Comment by paul-frost** [comment]
All good, really useful, thanks r043v
