### ISSUE TITLE
.fluidbox-ghost backgrounds are repeating

### ISSUE THREAD

**Issue by sukritchhabra** [terrymun/Fluidbox#131]
* The images are being set as backgrounds to `.fluidbox-ghost` but `background-repeat` isn't defined which is causing it to repeat behind the border;

* Solution would be to set `background-repeat: no-repeat;` and that fixes it

![lightboxerror2](https://cloud.githubusercontent.com/assets/6703126/9210357/d3e224c8-4049-11e5-91ba-cef94bbc7c6a.png)
![lightboxerror1](https://cloud.githubusercontent.com/assets/6703126/9210358/d3e302d0-4049-11e5-8eb3-465bde7a6898.png)

**Comment by terrymun** [comment]
This will be fixed in v2 :)
