### ISSUE TITLE
fluidboxLoading animation is running all the time taking CPU %

### ISSUE THREAD

**Issue by adi-** [terrymun/Fluidbox#134]

**Comment by terrymun** [comment]
This shouldn't be the case, because the animation is only enabled when the `.fluidbox-loading` class is there.

However the entire codebase is being rewritten as we speak, and I will ensure that this excessive CPU consumption does not go away unfixed.

**Comment by adi-** [comment]
Ok, but this doesn't concern FireFox. Animation, when hidden, is still computed...

**Comment by terrymun** [comment]
It is not hidden, but the class has been removed. The animation is only applied to the loader when the `fluidbox-loading` class is added. The class is removed once the target image has finished loading, and should therefore no longer be rendered.

**Comment by adi-** [comment]
Maybe should, but it is not in FF.
