### ISSUE TITLE
Prevent fluidbox from loading when a points to an anchor reference?

### ISSUE THREAD

**Issue by dtjohnso** [terrymun/Fluidbox#137]
I have an edge case that is incorrectly triggering fluidbox when images are wrapped in a link to an anchor somewhere on the current page.

My code will include a number of footnotes (generated automatically, I write in markdown and render to HTML using pandoc) that might look something like this:

```
<a href="#fnref17">↩</a></p>
```

Recently, my Wordpress theme (a child theme based on Twenty Thirteen) began replacing the ↩ character with an image. When I click these links to return to the footnote reference further up the page, fluidbox triggers, but of course never loads a full resolution image. Here's a recent example, try [any of the footnote return links at the end.](http://blogs.duncanjohnson.ca/ex401-fall-2015/lectures/lecture-2-introduction-to-the-psalms/) 

I suppose I could fix this by adding some CSS in my child theme to prevent the replacement of the  ↩ character with an image. But shouldn't fluidbox ignore links beginning with the '#' character anyway?

Thanks for any advice you might have if this is something I should just handle in my own fluidbox implementation.

**Comment by terrymun** [comment]
For now, you can simply restrict your selector further, i.e. `$('a:not([href^='#'])')` to select for anchor elements that do not have the `href` attribute beginning with `#`. The reasoning behind why Fluidbox does not conditionally restrict initialisation based on the `href` attribute is to let users have the highest degree of control over the Fluidbox selectors.

**Comment by dtjohnso** [comment]
Thanks, for the advice re the selector. I had forgotten that a selector was involved, so that's great as a quick fix.
