### ISSUE TITLE
The z-index and stackIndex values does not work properly

### ISSUE THREAD

**Issue by THPubs** [terrymun/Fluidbox#138]
In this page (https://188.166.247.70/products/P021962028 (I haven't modified the dns yet so ignore the ssl error)), I have added fluidbox. When I click an image, it enlarges. But the category menu goes right through the image! I gave the image a higher z-index but it won't work. How can I fix it?

PS : The category menu is from bootstrap.

**Comment by terrymun** [comment]
In order for Fluidbox's overlay to fully cover the page, it has to be in a parent that has the same stacking context as your menu. You can assign `position: relative` to their parents that are at the same level in the markup, and them assign the parent containing Fluidbox the higher z-index.

**Comment by THPubs** [comment]
Great thanks! One problem... Giving a higher z-index to the section fix the fluidbox. But now the dropdown menus will be hidden!

**Comment by THPubs** [comment]
Thanks a lot for the help :-) Just fixed the issue by adding this function to the onclick even of the link :

    <script>
        function setOverlay() {
            console.log("done");
            if ($('.inner-content').css('position') === 'relative') {
                $('.inner-content').css('position', 'static');
                $('.inner-content').css('z-index', 'auto');
            } else {
                $('.inner-content').css('position', 'relative');
                $('.inner-content').css('z-index', '99999999');
            }
        }
    </script>
