### ISSUE TITLE
Fluidbox picture appears always at the bottom of the page.

### ISSUE THREAD

**Issue by cregx** [terrymun/Fluidbox#140]
When I implement the basic configurated Fluidbox in a page, the opened picture appears only at the bottom of the page - sometimes in an unvisible area. This happens only in Firefox, Chrome but not in Internet Explorer 11.
Only when I use the deployed styles.css the behavior is like expected, but this destroys my own css style.

**Comment by terrymun** [comment]
If you use the deployed CSS and the plugin works, then it is not an issue with the plugin *per se*. You should them look at what are the overwritten styles between your own stylesheet and the one that came with Fluidbox.

**Comment by cregx** [comment]
I'm not sure if this is an issue, but I have to add body{ height: 100%; }" to my main.css and then it works in chrome and firefox also.

**Comment by terrymun** [comment]
Does your page have insufficient content to fill the viewport completely? If that's the case it might be explaining the visual glitch you are seeing. 

Otherwise create a reproducible, minimal example on JSfiddle or the likes, and we can have a look at it.
