### ISSUE TITLE
fluidbox.less Line: 55

### ISSUE THREAD

**Issue by SubZane** [terrymun/Fluidbox#141]
is
```
background-color: $animation-bg-color;
```
should be
```
background-color: @animation-bg-color;
```

**Comment by terrymun** [comment]
The LESS file has been deprecated. Fluidbox is now using SASS :) you're likely to be looking at an old release.

**Comment by SubZane** [comment]
Ah Understood :) However. The latest release available through bower is 1.4.3 and that release has a LESS file. Is the bower release old then maybe?

**Comment by terrymun** [comment]
I am not sure why the LESS file is still being distributed—I'll have a look at it.

**Comment by SubZane** [comment]
Cool. Anyway when using the SASS or CSS instead from you master bransch everything works as intended again :)

**Comment by terrymun** [comment]
Thanks! I'm rewriting the code base for v2, and will be using grunt to compile all the sources—that should tie up all the loose ends :)
