### ISSUE TITLE
Code revision: Implement Gulp.js and simplify directory tree

### ISSUE THREAD

**Issue by maxee** [terrymun/Fluidbox#142]
As suggested in one of my MR #107, using gulp.js would make development easier.
Maybe this can be included into the v2 code revision.

**Comment by terrymun** [comment]
Thanks for the heads up @maxee! I have decided to work with grunt for development and distribution.

**Comment by maxee** [comment]
@terrymun perfect! Yeah if gulp or grunt, that doesn't matter. Both do a good job :)

**Comment by terrymun** [comment]
Grunt has been installed, check the latest release ;) thanks for all the advice!
