### ISSUE TITLE
Implement slider

### ISSUE THREAD

**Issue by SndrL** [terrymun/Fluidbox#144]
First of all thank you for this wonderful plugin!

Wouldn't it be great if a user clicks on an image, fluidbox opens, and it kinda acts like a slider for the following images?

**Comment by terrymun** [comment]
This is analogous to the gallery feature requested—and it has been discussed that this feature will not be implemented to keep Fluidbox simple. See #52.

**Comment by SndrL** [comment]
:+1: Thanks for the response, I completely agree with your decision to keep it simple. Although I think in some situations a gallery/slider function would be awesome! We'll see what future forks bring :)
