### ISSUE TITLE
Scroll enhancement

### ISSUE THREAD

**Issue by aaronstezycki** [terrymun/Fluidbox#145]
A small addition to UX, instead of a user scrolling down and just getting a white a screen, after say 1s of scrolling, the opened image returns to its initial  pre-clicked state.

**Comment by terrymun** [comment]
You can customise what triggers the Fluidbox closing method via the `closeTrigger` setting—please refer to the documentation on usage. However, this method cannot be modified (like the timeout you suggested) unless you change the source. This issue will be mitigated in v2.

Fluidbox aims to give the end-user the largest degree of control, and therefore does not set out to dictate what kind of interaction will trigger what kind of behaviour, besides the basic click event.

Note that the `closeTrigger` option will be deprecated in v2, where Fluidbox will support calling public methods through the `.fluidbox()` method, e.g. `.fluidbox('close')`. In the future, you can trigger closing of a Fluidbox instance in any way possible:

```js
// Initialise Fluidbox
$('a').fluidbox();

// Listen to scroll
$('window').scroll(function() {
    window.setTimeout(function() {
        $('a').fluidbox('close');
    }, 1000);
});
```

**Comment by aaronstezycki** [comment]
Thanks @terrymun, can't wait for version 2.

**Comment by terrymun** [comment]
v2 is already released ;) still working on the CDNJS update though.

**Comment by aaronstezycki** [comment]
:+1:
