### ISSUE TITLE
Doesn't 'really' support different ratios

### ISSUE THREAD

**Issue by aaronstezycki** [terrymun/Fluidbox#148]
If image thumbnails are a different size to that of the expanding image, there usually a visual jump between the thumb and the enlarged images. 

It's probably best to advise developers that thumbnails *should* be the same ratio as the enlarged image to stop clunky animations.

You can see this directly from your demo page. When the enlarged image (3840x2k) scales down to match the thumbnail (200 x 200) you can see the text is squished. This would be same for a photo.
http://terrymun.github.io/Fluidbox/demo/index.html

Attached a gif also.
![screen capture on 2015-10-19 at 15-08-04](https://cloud.githubusercontent.com/assets/5744600/10580017/53b65980-7673-11e5-8394-512b3b1d0d6f.gif)

**Comment by terrymun** [comment]
I think it's a bit of an interpretation issue. If you look back towards the earlier incarnations of Fluidbox, it only supports opening images that have the exact same aspect ratio as the thumbnail. By intuition it is obvious that Fluidbox will work best with images of identical aspect ratios.

There is no easy way to fix this visual compression issue when dealing with differential aspect ratios, and it will be the way it is for now.
