### ISSUE TITLE
FluidBox opens surrounding link (href) when image is opened in Firefox 41.0.2

### ISSUE THREAD

**Issue by aramin** [terrymun/Fluidbox#151]
Yesterday I updated FluidBox from 1.4 to 2.0 and realized that in Firefox 41.0.2 the link of an image is opened after the image was clicked. I could hotfix that behavior with a e.stopPropagation() (directly after e.preventDefault()) in line 524.

**Comment by terrymun** [comment]
If you need stop event propagation to stop an image from opening, it suggests that there's something else on your page that is muddling up Fluidbox behavior. Are you listening to a click event propagation higher up the DOM tree?

Also stopping event propagation would break a lot of things if implemented. For example, what if a user is listening to a bubbling click event to perform a silent AJAX request? That'll be rendered non-functional if we choose to stop events from bubbling up. 

Helpful tip: try using your markup in the packaged demo, and see if you can reproduce the issue.

**Comment by aramin** [comment]
Thanks for the rapid response! :+1:
I also tried the demo-page and experienced the same behaviour (e.g. when I click on the single image http://terrymun.github.io/Fluidbox/demo/index.html#single-image). So I would assume that it's not related to my code/DOM-structure.

**Comment by terrymun** [comment]
I am unfortunately unable to replicate your issue on v41 and v42 of Firefox tho.

**Comment by aramin** [comment]
Maybe it's a Windows-only issue. I just tried it with FF 42 and im still facing the problem. I'll test it on monday on an OSX system.

The system where the error occured is as following:
Windows 8.1 Pro
Firefox 42.0

**Comment by terrymun** [comment]
I have tested the demo page using BrowseStack, on both Windows and OS X FF v41. Still unable to reproduce your issue.

Do you have some plugins/addons that are installed on your browser that might potentially interfere with Fluidbox functionality? Ad-blockers, content filters and the likes, perhaps?

**Comment by aramin** [comment]
Ok, I just tried it on a Mac with OSX Yosemite FF 42.0 and everything works like a charm.

**Comment by aramin** [comment]
The problem is caused by the addon "AS Magic Player". So everything is fine and I'm sorry for the inconvenience.
