### ISSUE TITLE
srcset ?

### ISSUE THREAD

**Issue by SheepDomination** [terrymun/Fluidbox#152]
Hi, does Fluidbox work with srcset, rather then `<picture>` ?

**Comment by terrymun** [comment]
Not that I know of, however, if the image source(s) (and hence dimensions) is/are updated upon viewport resize, Fluidbox should be able to handle that.

You can try testing it yourself, and report back if you have any issues.

**Comment by SheepDomination** [comment]
scrset isn't working;

The image is an anchor; when clicking on the image anchor, instead of the first image which is part of the srcset loading, the same image that is for the anchor loads ?

**Comment by terrymun** [comment]
Can you create a minimal, concrete and verifiable example?

**Comment by SheepDomination** [comment]
<p class="imgbox left">
                  <a href="/wdp/wip/paperpile.png" class="firstimg">
                   <img src="/wdp/wip/images/paperpile.png"
                    srcset="/wdp/wip/images/brick.jpg 320w,
                    /wdp/wip/images/bulding.jpg 560w,
                    /wdp/wip/images/rock.jpg 900w"
                      sizes="(min-width: 320px)"
                     alt="" title="">
                </a>


This is strictly the markup, as you stated minimal. Another issue with fluid box is; and this is a little tougher to describe.  The image loads; but there is a opaque white screen to which covers up the entire page ? If that description wasn't clear, I probably have to send a screen shot, unless you are able to decipher what I meant ?

**Comment by SheepDomination** [comment]
Any idea ?

**Comment by terrymun** [comment]
I've been quite busy lately, so forgive the slow replies.

A quick fix would be to responsively change the anchor's `href` attribute according to the viewport size, in line with the specifications in your `srcset` attribute. Fluidbox does not currently have an internal function that changes the source of the background image that is dependent on screen/viewport size.

p/s: Updated your comment for markup formatting.

**Comment by SheepDomination** [comment]
I don't understand what you mean; when you say;
-- A quick fix would be to responsively change the anchor's href attribute according to the viewport size, in line with the specifications in your srcset attribute. Fluidbox does not currently have an internal function that changes the source of the background image that is dependent on screen/viewport size.--

**Comment by terrymun** [comment]
Your issue is that Fluidbox references the same image regardless of screen size. Therefore you can programatically change this reference (Fluidbox reads from the `href` attribute of the anchor) based on viewport breakpoints that you have also specified in your srcset. Definitely not the most straightforward way, but...

If you have any further question I would suggest creating a concrete and minimal example, on Codepen, JSFiddle, etc., and we can dabble on it as we go along.

**Comment by SheepDomination** [comment]
Do you have an email where I can reach you; so there isn't a large gap between communication and we can speed this up ?

**Comment by terrymun** [comment]
I'm sorry, but I do not provide email support for publicly-released, free-of-charge and provided as-is plugins—it opens a dangerous precedent. [See point no. 5 in the FAQ section of the readme](https://github.com/terrymun/Fluidbox#frequently-asked-questions).

**Comment by SheepDomination** [comment]
Here is a JSFiddle (http://jsfiddle.net/WildWind/r7d1085z/embedded/result/), there is no way to test within JSFiddle a responsive image the goal is; the image to which everyone will see is the paperpile image, when the user clicks on the paperpile image on a 320px width, for example, an iPhone.  The brick image should show, etc etc.  

If I understand you correctly; I have to add like a min-width attribute to the srcset, then, and only then will fluidbox understand and display the correct image ?

**Comment by ismay** [comment]
@SheepDomination I don't think that'll work. The image that fluidbox displays onClick is the image from the `<a href="this image">`. The `srcset` within the `<a>` will only be used for the thumbnail.

I think something like bbc's [imager.js](https://github.com/BBC-News/Imager.js/) could be useful here. If you run it before the fluidbox script you should be able to optimize all your images before fluidbox gets to them.

Then for further optimisation you could make sure that on resize imager runs again, before fluidbox does.

**Comment by terrymun** [comment]
Thanks @ismay for the clarification. This issue will be closed because of no further recent activity.
