### ISSUE TITLE
Parentheses in filename

### ISSUE THREAD

**Issue by afivos** [terrymun/Fluidbox#155]
Let me start by saying I love Fluidbox. It's the best of its kind I've found so far.

I discovered that it won't work with images that include parentheses in their filenames. I troubled me quite a bit so I thought I'd let you know.

**Comment by terrymun** [comment]
That is because you will have to escape the parentheses character—in other words, you will have to encode the URL in the anchor element, in conformance with RFC3986. 

This issue has been raised before, but with other characters the needs to be encoded: #112 and #113.

**Comment by afivos** [comment]
Ok, thanks for letting me know.

**Comment by terrymun** [comment]
The decision to replace parentheses characters are being under due consideration, see #156.
