### ISSUE TITLE
"Matt Bailey's excellent guide on setting up Grunt" now 404s

### ISSUE THREAD

**Issue by DJDavid98** [terrymun/Fluidbox#157]
The link (http://mattbailey.io/a-beginners-guide-to-grunt-redux/) used in the readme under "Building with Grunt" (as well as the "Special thanks" section) now displays a generic error page <del>instead of the useful resource it probably was at some point. I suggest that the sentence</del>

><del>If you are new to this, kindly refer to Matt Bailey's excellent guide on setting up Grunt.</del>

<del>should either be removed or updated with an equivalent guide.</del>

Apparently, it's because of the `/` at the end, changing the link to http://mattbailey.io/a-beginners-guide-to-grunt-redux displays the proper page.

**Comment by terrymun** [comment]
That error was discovered and reported to the author.
