### ISSUE TITLE
Bug with "scroll to close" example.

### ISSUE THREAD

**Issue by rrikesh** [terrymun/Fluidbox#161]
I'm having an issue with the [Custom Triggers](http://terrymun.github.io/Fluidbox/demo/index.html#custom-triggers) part where there's an example of scrolling to close an opened image.

After opening the example image, scrolling closes the Fluidbox as expected. However clicking on the image again doesn't open it again in the Fluidbox. The image is opened when it is clicked for the second time.

I got the same issue on Firefox/Chrome/Safari on Mac.

**Comment by terrymun** [comment]
Thanks for the heads up! It turns out that the `instanceData` object is not updated properly when a manual close event is triggered. This has been rectified in the commit ebd88e2.

This fix will also be reflected in the imminent v2.0.2 release :)

**Comment by rrikesh** [comment]
Awesome, thanks!
