### ISSUE TITLE
Forgotten console.log Statement In Production

### ISSUE THREAD

**Issue by superKalo** [terrymun/Fluidbox#162]
Hey @terrymun,

Thanks for the great plugin!

I spot you left one console.log statement in production, here https://github.com/terrymun/Fluidbox/blob/master/src/js/jquery.fluidbox.js#L535 (also exists in the minified version). I believe it shouldn't exist in production ;-)

Greetings,
Kalo.

**Comment by terrymun** [comment]
Thanks for the heads up! This has been resolved in the latest commit 5728db.

**Comment by superKalo** [comment]
You're welcome :+1:
