### ISSUE TITLE
Dynamic blur overlay image?

### ISSUE THREAD

**Issue by telakaya** [terrymun/Fluidbox#166]
how can i add dynamic blur overlay image
` $(".ddda a").on('openstart.fluidbox', function () {
           
            var bakimg = $(this).attr("href");
            $(".overlay-3 .fluidbox__overlay:before").css("background-image", "url(" + bakimg + "))!important")
        });`
this not work :(

**Comment by terrymun** [comment]
Unfortunately JS do not have access to pseudo-elements, because they are not part of the DOM. Therefore you will have to declare it from within a stylesheet, by either doing so in your CSS, or using JS to inject a `<style>` element in your document.
