### ISSUE TITLE
Breaks all other image links

### ISSUE THREAD

**Issue by mrtnsimo** [terrymun/Fluidbox#170]
Hi,

I put fluidbox on my ghost. The images in function great now. 

All other image links have stopped working though. The logo in top left corner no longer works. I also have images in the homepage post loop. These link to posts themselves and have also stopped working.

**Comment by terrymun** [comment]
With no code or example, it will be impossible for me to help you troubleshoot. Here's what you can do:

1. Run the demo of fluidbox on your server. Does it work?
2. Implement that code on your site with minimal modifications. Does it work?
3. Keep adding other components until something breaks. 

Check your console log in between and try to find where the error is coming from.

**Comment by mrtnsimo** [comment]
Hi Terry,

thanks for the quick reply. I will try to provide some more context.

I am using ghost for our company blog and have made some slight modifications to the default casper theme. The problem with fluidbox occured in all image links outside that were not pard of content. These are images, e.g. logo that link to a different site. 

These seem to fit the definition of fluidbox selector even though the target url is not an image. This then creates a problem which breaks these links.

I implemented fluidbox guided by this article: https://www.ghostforbeginners.com/add-an-image-lightbox-to-ghost/

A link to our blog is: http://blog.paravan.sk

I have since removed the fluidbox code. I will try to find a solution during weekend. Will update, if I come up with something.

**Comment by terrymun** [comment]
You can just use a more stringent selector for the anchor links that you want Fluidbox to initialize with, e.g. `$('.content a')` or the likes.

**Comment by terrymun** [comment]
@twang91 It seems like the selector of choice, `.post img` is too broad and causing Fluidbox to be instantiated on images that do not strictly belong to the post content (therefore affecting other images).

**Comment by twang91** [comment]
@terrymun I actually got it working by changing the class to a rel attribute and placing it on the anchor tag instead of the img tag.
