### ISSUE TITLE
Gallery navigation

### ISSUE THREAD

**Issue by SimonFricker** [terrymun/Fluidbox#173]
Please add gallery navigation to the next release. Eg, using left and right arrows to navigate to the next/previous one.

**Comment by paul-frost** [comment]
I'm sure Terry is getting fed up with people repeatedly asking this question. It was only asked and replied to in issue [#172](https://github.com/terrymun/Fluidbox/issues/172) 7 days ago (the previous issue in fact).

Can I suggest that you look at the Closed issues before posting a question, as there is a good chance the question has been asked before. Terry provides this code for free, but the time he spends answering the same questions repeatedly means the less time he will have to keep the code updated. He might also get fed up and stop responding to genuine issues.

**Comment by terrymun** [comment]
See #52.
