### ISSUE TITLE
viewportFill doesn't scale up an image

### ISSUE THREAD

**Issue by janstieler** [terrymun/Fluidbox#176]
Hi,
viewportFill doesn't work.
It scale not my image it open it in the same size I have it in HTML. Is a second bigger image needed for that?
Is there a possibilitie to scale up a image?

Cheers

**Comment by terrymun** [comment]
I don't think this was mentioned explicitly on the readme, but it is briefly talked about on the demo page itself:

> Fluidbox is also built to handle linking to images that do not have the sufficient size to fill the page. The following thumbnail links to an image that is only 250×250px large — in most cases, insufficient to fill the viewport (unless you are using this site on a very small viewport).

Therefore, if your image does not have the necessary resolution to fill up the viewport, the viewportFill option will be ignored. There is no way to blow up an image unless you provide a higher resolution alternative.

You can hack your way through this restriction by modifying the code around line https://github.com/terrymun/Fluidbox/blob/47db04be9250bd3b570c4c040a989987f984e6d0/src/js/jquery.fluidbox.js#L483-L493.

**Comment by terrymun** [comment]
This issue will be closed due to non-activity and because it is a deliberate design decision.
