### ISSUE TITLE
Bug (low) : Duplicate .fluidbox__overlay if href is wrong path (404)

### ISSUE THREAD

**Issue by l2aelba** [terrymun/Fluidbox#179]
I just report a bit bug here : When `href` set with a wrong path

**Example :**
```html
<a class="fluidbox" href="if_this_is_a_wrong_path"><img src="http://placeimg.com/640/480/arch.jpg"></a>
```

When I clicking `<a>` so `.fluidbox__overlay`will appended each time. _(10 times = 10 .fluidbox__overlay)_

**Comment by terrymun** [comment]
This arises due to `transitionend` events not being fired on the ghost element if the image fails to load, because no calculations and hence scaling will take place.

This issue is fixed in 465adbb.
