### ISSUE TITLE
"Single image" example on demo page does not open

### ISSUE THREAD

**Issue by Mesoptier** [terrymun/Fluidbox#185]
Tested in a bunch of common browsers (Chrome 56, Firefox 51, IE 11, etc.). I can see some classes/styles being added, but the images does not move to a fullscreen overlay.

http://terrymun.github.io/Fluidbox/demo/index.html#single-image

**Comment by terrymun** [comment]
Seems like the link is broken due to accidental insertion of two `ss` characters. Fixed in 0698be5.
