### ISSUE TITLE
data-fluidbox-max-width no working correctly.

### ISSUE THREAD

**Issue by bennyb** [terrymun/Fluidbox#186]
Hoping to give each elements it's own max width as some I need to allow for some caption text to the right.  But setting the max-width data attribute seems to make the image shrink when clicked.

See example.
https://jsfiddle.net/bennyb/f3z8f2kz/

**Comment by terrymun** [comment]
I confirm that the is a bug. This is due to the erroneous coercing of HTML5 `data-` attribute values into `true`, when it is not `false`. Fixed in 46c19a2 :)
