### ISSUE TITLE
Navigate Fluidbox with Arrow Keys

### ISSUE THREAD

**Issue by spieglio** [terrymun/Fluidbox#191]
Hello - I just found this jQuery plugin and feel like it's the most beautiful / minimalist lightbox I have seen and would love to use it. But I have one feature which I wonder if it's doable via customization with this plugin (or if it's part of the roadmap).

I'd like to be able to navigate photos inside my article with the left and right arrow keys (cycle through the images basically).

Is this something I could achieve with customization?

It'd be super helpful and thanks in advance,
Chris

**Comment by terrymun** [comment]
I think this is related to the gallery function? Do correct me if I have understood your question incorrectly.

See #52 :)

**Comment by spieglio** [comment]
Yes, kinda does fall into that topic area. Sorry for not getting that int he first place.
I'll stay without arrow key navigation for now then :) I totally understand how this keeps it simple and smaller.
