### ISSUE TITLE
help conflict with mcustomscrollbar

### ISSUE THREAD

**Issue by ptitof** [terrymun/Fluidbox#195]
first of all thank you for this beautiful program, I have an integration problem with mcustomscrollbar. Could not get the image out of the container using mcustomscrollbar. I tried with z-index, but the problem did not come from an overlay property. Everything works that I disable mcustomscrollbar. Is there a function in js for fluidbox to dominate a container already using a js program with a higher priority?

thank you

**Comment by terrymun** [comment]
The plugin is probably creating a new stacking context, which means Fluidbox is unable to break out of it. See: https://github.com/terrymun/Fluidbox#accidental-creation-of-new-stacking-contexts

**Comment by terrymun** [comment]
Closing due to non-response from OP.
