### ISSUE TITLE
Zoomed image stays blurred in MacBook

### ISSUE THREAD

**Issue by dvdchr** [terrymun/Fluidbox#67]
This works just fine in Windows, Linux, Ubuntu. The thumbnail is of 70x120, and the real image is 700x1200 (10x scale).

Any idea what might cause this? Is it the scale that's too big?

**Comment by anthonyabraira** [comment]
That didn't correct it for me. Instead I found that the `animation: fluidboxLoading 1s infinite;` was doing it. I disabled it with a little CSS with rule: `.fluidbox-ghost:before { animation: none;}`
