### ISSUE TITLE
Active image appears underneath other fb ghosts. 

### ISSUE THREAD

**Issue by gr33k01** [terrymun/Fluidbox#92]
Hey there,

My guess is that this is a implementation-specific issue, so I thought it would be helpful to get your eyes on it. 

If you head over to [this link]( http://lakeintegritylawn.com/fluidbox-issue/) and scroll down to the 'Recent Work' section, you'll see a bunch of images. This is where I'm trying to implement your plugin and I'm seeing this pattern: 

* The first image is underneath all other ghosts when active.

* The second image is underneath all other ghosts except the first image when active.

* The third image is underneath all other ghosts except the first and second images when active.

etc...

* The last image is fine.

Seems like a z-index issue, but I'm not applying any z-index to the elements myself and they should be at the default static positioning. I'm going to keep tooling around with it but I would love your thoughts.

Thanks.

**Comment by terrymun** [comment]
I suspect it is because you are individually wrapping each `<img />` with `<div class="recentWork-item">`, resulting a new stacking context being created. I have no idea why this is happening, but perhaps there are other interfering styles?

**Comment by gr33k01** [comment]
Hey, thanks for the follow up. Think I found the issue here. I had a CSS grayscale filter on the 
```html 
<div class="recentWork-item">...</div>
``` 
and when I removed that, everything was peachy. 


When I target the actual image tags and add the CSS filter (instead of the parent container), it works as well. Crazy. Tried to look into known issues with CSS filters messing with z-index/positioning, but I couldn't find anything. 

Definitely test this for yourself, but it looks like CSS filters will break this unless they're on the image tag? It makes sense to use CSS filters strictly on image tags, but this behavior might be worth noting. 

Thanks again for your input.

**Comment by terrymun** [comment]
I did a little more digging, and apparently there are a few CSS properties, when applied to the wrapping parent of elements meant for the `.fluidbox()` method, causes a new stacking context to be created — and CSS filters are just one of them.

They are, in alphabetical order but not exhaustively so:
- CSS3 regions<sup>1</sup>
- filter<sup>1, 2</sup>
- flex<sup>3</sup>
- isolation<sup>3</sup>
- mix-blend-mode<sup>3</sup>
- opacity<sup>1</sup>
- position<sup>1, 3</sup>
- paged media<sup>1</sup>
- transform<sup>1</sup>
- will-change<sup>3</sup>

Sources:
1. [*What No One Told You About Z-Index*](http://philipwalton.com/articles/what-no-one-told-you-about-z-index/) by Philip Walton
2. [*Why does stacking order change on webkit filter hover?*](http://stackoverflow.com/a/25764603/395910) on StackOverflow
3. [*The stacking context*](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context) on MDN

I'll add that as a usage precaution to the project's readme. Thanks for spotting! :)
