### ISSUE TITLE
Skeljs + Fluidbox (glitchy)

### ISSUE THREAD

**Issue by anthonyabraira** [terrymun/Fluidbox#95]
So I did several things to lay the stage here. I created a template based off of the Murtaugh HTML5 Reset Wordpress theme. 

Then I added the skel responsive framework by adding the script via the functions.php file:

```
//* N33 SKELJS
add_action( 'wp_enqueue_scripts', 'enqueue_and_register_skeljs' );

function enqueue_and_register_skeljs(){

// Use `get_stylesheet_directoy_uri() if your script is inside your theme or child theme.
wp_register_script( 'skeljs', get_stylesheet_directory_uri() . '/_/js/skel.min.js' );
wp_register_script( 'skeljs-layers', get_stylesheet_directory_uri() . '/_/js/skel-layers.min.js' );
wp_register_script( 'skeljs-init', get_stylesheet_directory_uri() . '/_/js/skel.init.js' );

wp_enqueue_script('skeljs' );
wp_enqueue_script('skeljs-layers');
wp_enqueue_script('skeljs-init');
}
```
Then did the same thing for the Fluidbox plugin:

```
//* FLUIDBOX
add_action( 'wp_enqueue_scripts', 'enqueue_fluidbox' );
function enqueue_fluidbox() {
	wp_enqueue_style( 'fluidbox-css', get_bloginfo( 'stylesheet_directory' ) . '/_/inc/css/fluidbox.css', array(), CHILD_THEME_VERSION );
	wp_enqueue_script( 'fluidbox', get_stylesheet_directory_uri() . '/_/inc/js/jquery.fluidbox.min.js', array( 'jquery' ), '1.0.0', true );
	wp_enqueue_script( 'fluidbox-init',  get_stylesheet_directory_uri() . '/_/inc/js/fluidbox.init.js', array( 'fluidbox' ), '1.0.0', true );
	}
```

<h3>Current Issue</h3>
What's interesting that if I load the page and try to click on one of the images, it goes directly to the JPG source of the image and loads just the image. But when I click "back" on my history and click on the activated images (via the .fluidbox class) the zooms work? 

What's different from arriving at a page directly in contrast to back pedaling through your history that permits fluid box to work only then? 

I have tried having the fluid box js stuff load at the header (after JQuery) and at the footer.

**Comment by terrymun** [comment]
Based on your description it seems that the reason why Fluidbox failed to work at the first time is likely due to the images dimensions being inaccessible to the plugin. When you navigate backwards the images are loaded from the cache and therefore instantly accessible. 

Here are somethings you can try:

 - When the page is first loaded, check the images which have Fluidbox initialized with. Are the `.fluidbox-ghost` element the right dimensions? Does it even exist? What error messages do you see in the browser console log?
 - Run the page without Skeljs being loaded. Can you still replicate the issue? 
 - Create a minimal, concrete and verifiable example to demonstrate the problem (e.g. on JSFiddle) if you need me to have a closer look

**Comment by anthonyabraira** [comment]
I will post up a working demonstration.

I can tell you that by disabling scale JS it was working fine.

Once I have the link I will send it to you

**Comment by terrymun** [comment]
It seems that the `.fluidbox-ghost` element has a dimension of zero, indicating that the source image computed dimensions are inaccessible to Fluidbox upon DOM ready. There might be many reasons why this is happening, including hiding the images (or any of its ancestors, be it the wrapping element or even the body element). When images are hidden directly or indirectly, their computed dimensions are inaccessible to JS.

I have no idea what is causing this behaviour, and I have asked the questions in my previous comment but you seemed to have not read and responded to them.

You can link any image file you want to the thumbnail. The aspect ratio do not have to be identical, and they can be of different source files. It does not really matter what images you are linking, as long as you are using the standard `href` attribute in the anchor link, i.e.:

```
<a href="/path/to/image">
    <img src="/path/to/thumb" alt="" title"" />
</a>
```

**Comment by anthonyabraira** [comment]
Apologies for not answering your previous questions. Moreover not properly reading your website which clearly indicated that you had the means of linking to a higher resolution file. Oddly enough, I have been able to get the image to sometimes work on my site but, as you said, it seems mostly due to the cache.

1. Without Skeljs turned on — Fluidbox works fine. 

I was going to try and put together a small minimal standalone HTML5 page with both of the participating libraries (skel & fluid) but did a web search instead and came across a variety of threads that pointed to this primarily or likely to be CSS. 

There I found that I had formalize.css spitting a bunch of small time errors in the console. Seeing that I wasn't using it — it came with the Murtaugh Reset Wordpress theme — I now see things responding well.

**Comment by anthonyabraira** [comment]
Unfortunately my fix was only temporary. I can see what you mean now about the 'fluidbox-ghost' element not getting the width and height attributes. The screen shot indicates this:

![screen shot 2015-01-26 at 7 54 54 pm](https://cloud.githubusercontent.com/assets/3163617/5911579/5957fa9c-a595-11e4-8f18-b275efe36c10.png)

Now what's interesting was when I resized the image a little it put in the proper properties:

![screen shot 2015-01-26 at 7 55 01 pm](https://cloud.githubusercontent.com/assets/3163617/5911581/67a1801e-a595-11e4-9b5a-eefe9079b009.png)

Now when I read your README file I noticed that you had also mentioned this known issue. I tried to apply this code:



I did this by adding it to the functions.js which executed after JQuery, SkelJS and fluid box:

```
(function($){


/* trigger when page is ready */
$(document).ready(function (){
$('body').css('opacity', '0').fadeTo(500, 1,'swing').removeClass('hidden'); 
	
	
$(function(){ $(".Fname").focus(); });	
});


$(window).load(function() {


			
			// Do this AFTER Fluidbox has been initialized
			$('.the_content').each(function() {
			var images = [],
			$fb = $(this).find('a.fluidbox');
			
			$f.find('img').each(function() {
			var image = $.Deferred();
			$(this).load(image.resolve).error(image.resolve);
			images.push(image);
			});
			
			$.when.apply(null, images).done(function() {
			$fb.trigger('recompute');
			});
			});


	
});
```
 
This coughed up an error with regards to the line:

![screen shot 2015-01-26 at 7 54 38 pm](https://cloud.githubusercontent.com/assets/3163617/5911588/80f9b928-a595-11e4-9a16-c5ebaf08f7db.png)

```
$f.find('img').each(function() {
```

**Comment by terrymun** [comment]
I visited the URL you mentioned, and all Fludibox instances seem to be working fine for me. Tested on Chrome v41.

**Comment by anthonyabraira** [comment]
Yeah the issue arose when I tried to use the no-js body class to make all of the content appear (via the display CSS) property. Going to use an overlay to achieve the same effect.

**Comment by terrymun** [comment]
Has this issue been resolved?
