### ISSUE TITLE
Fluidbox Wrap Slightly Bigger Than Image

### ISSUE THREAD

**Issue by realph** [terrymun/Fluidbox#97]
I'm using Fluidbox for the first time, but I've noticed that the `fluidbox-wrap` element's `height` seems to be around 4px bigger than the image I'm using. 

I've created a CodePen of the issue I'm having [over here](http://codepen.io/realph/pen/pvwQod).

Does anyone know how to fix this? Am I doing something wrong?

**Comment by terrymun** [comment]
The `<img />` element is an inline element by default. Simply set it to `display: block` so that will fix the baseline issue

**Comment by realph** [comment]
@terrymun Good god. Please forgive my stupidity.

**Comment by terrymun** [comment]
Please don't say that. There's nothing stupid about that!
