### ISSUE TITLE
Css animations

### ISSUE THREAD

**Issue by colir** [terrymun/Fluidbox#98]
Hi.
First at all , thanks for your plugin ;)

I've corrected an issue with the css animations on firefox (no animation at all).
To fix it, i added the 's' to all the timing animation properties when you write 0( must write 0s)
After that, all work well

**Comment by terrymun** [comment]
Can you submit a PR? I will merge it, thanks! :+1:

**Comment by colir** [comment]
I tried...but not really sure how to do that...
perhaps you can help me if my manipulation is not the right one.
thanks

**Comment by terrymun** [comment]
Already fixed :)
